apiVersion: v1
kind: Pod
metadata:
  name: ks-pod-env
spec:
  containers:
    - name: ks-pod-env
      image: busybox
      command:
        - sleep
        - "10000"
      env:
        - name: SECRET_CONFIG
          valueFrom:
            secretKeyRef:
              name: ks-secret-config
              key: config.yaml
  restartPolicy: Never